version: '3.9'

services:

  db:
    container_name: chain-db
    image: mariadb
    restart: always
    environment:
      MARIADB_USER: admin
      MARIADB_ROOT_PASSWORD: foo
    volumes:
      - data:/var/lib/mysql

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
