name: Test Compose

on:
  push:
    branches: [develop]
  pull-request:
    branches: [develop]

jobs:
  run-tests:
    name: Run cypress tests
    runs-on: ubuntu-latest
    container:
      image: compose:latest
      volumes:
        - my-app:/app
      steps:
        - name: Running compose install
          run: composer install
        - name: Running cypress E2E test
          run: .