name: Docker 2

on:
  push:  
    branches: 
      - develop
  pull-request:
    branches:
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with: 
          node-version: '20'
      - name: Install dependencies
        run: |
          cd ./testChain
          npm install
          npm install cypress --save-dev
          npx cypress run
