# Example for a GitHub Actions workflow file (.github/workflows/ci.yml)
name: E2E

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Run Cypress tests
      run: cd testChain
      run: npx cypress run
