name: Test E2E

on:
  push:  
    branches: 
      - develop
      

jobs:
  test-code:
    name: Test E2E
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Run cypress
        working-directory: ./testChain
        run: npx cypress run