name: Cypress Tests using Cypress Docker Image

on:
  push:
    branches:
      - develop

jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    container:
      image: cypress/browsers:node-20.9.0-chrome-118.0.5993.88-1-ff-118.0.2-edge-118.0.2088.46-1
      options: --user 1001
    steps:
      - uses: actions/checkout@v4  # Keep only the latest version

      - name: Install dependencies
        run: npm install  # Install dependencies within the container

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build  # Assuming build command is correct
          start: npm start      # Assuming start command is correct
          browser: chrome
