name: Test run

on:
  push:  
    branches: 
      - develop
      

jobs:
  test-code:
    name: Test E2E
    runs-on: ubuntu-latest
    steps:
      - name: Install cypress
        uses: cypress-io/github-actions@v6
        with:
          build: npm run build
          start: npm start
          